name: Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: npm run coverage
